FROM ruby:2.4.3-alpine
MAINTAINER Peter Mac <peter@petermac.com>

RUN apk add --update --no-cache \
      build-base \
      nodejs \
      tzdata \
      libxml2-dev \
      libxslt-dev \
      postgresql-dev \
      bash

ENV APP_HOME="/usr/src/app" \
  DOCKER_DIR="/usr/src/docker" \
  PATH="/ruby_gems/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

RUN mkdir -p ${APP_HOME} && \
  mkdir -p ${DOCKER_DIR}
WORKDIR $APP_HOME

COPY Gemfile ${APP_HOME}/
COPY Gemfile.lock ${APP_HOME}/
COPY ./docker/* ${DOCKER_DIR}/

ENV BUNDLE_GEMFILE=${APP_HOME}/Gemfile \
  BUNDLE_PATH="/ruby_gems" \
  BUNDLE_JOBS=20 \
  BUNDLE_RETRY=5 \
  GEM_HOME="/ruby_gems"

RUN gem install bundler

EXPOSE 3000
